# docker stack deploy -c docker-compose.yml perf
version: '3.5'

services:
  perf:
    image: abilioesteves/perf:0.0.4
    build: .
    ports:
      - "17333:17333/tcp"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s
