# docker stack deploy -c docker-compose.yml perf
version: '3.5'

services:
  perf:
    build: .
    image: abilioesteves/perf:0.1.13
    ports:
      - "17333:17333/tcp"
    environment:
      - WRITE_PATH=/
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s

  prometheus:
    image: abilioesteves/prometheus
    volumes: 
      - promdata:/prometheus
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=diskperf@perf:17333/diskperf/prom
      - DNS_SCRAPE_TARGETS=
      - SCHEME_SCRAPE_TARGETS=http
      - REMOTE_WRITE=
      - REMOTE_READ=
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s
    
volumes:
  promdata: